// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIvF1byxO4hNcAPtr6SqPCNovcZnUTqU',
    appId: '1:760619551268:web:27bbe7fc044d9ff14fa6b1',
    messagingSenderId: '760619551268',
    projectId: 'bokk-yoon',
    authDomain: 'bokk-yoon.firebaseapp.com',
    storageBucket: 'bokk-yoon.firebasestorage.app',
    measurementId: 'G-QBQD1MJWVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiH_w-xcSpiHQH4UZO9E5vQbCKUs4vlMA',
    appId: '1:760619551268:android:8e3e436c4fc090f44fa6b1',
    messagingSenderId: '760619551268',
    projectId: 'bokk-yoon',
    storageBucket: 'bokk-yoon.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJL4rmO5fODQsWNm-TonIyc31uz7NrOU',
    appId: '1:760619551268:ios:446c623e6d3cad054fa6b1',
    messagingSenderId: '760619551268',
    projectId: 'bokk-yoon',
    storageBucket: 'bokk-yoon.firebasestorage.app',
    iosBundleId: 'sn.uam.bokkYoon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJL4rmO5fODQsWNm-TonIyc31uz7NrOU',
    appId: '1:760619551268:ios:446c623e6d3cad054fa6b1',
    messagingSenderId: '760619551268',
    projectId: 'bokk-yoon',
    storageBucket: 'bokk-yoon.firebasestorage.app',
    iosBundleId: 'sn.uam.bokkYoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIIvF1byxO4hNcAPtr6SqPCNovcZnUTqU',
    appId: '1:760619551268:web:7ccac7c432c49d4b4fa6b1',
    messagingSenderId: '760619551268',
    projectId: 'bokk-yoon',
    authDomain: 'bokk-yoon.firebaseapp.com',
    storageBucket: 'bokk-yoon.firebasestorage.app',
    measurementId: 'G-8QWNDK6K4B',
  );
}
